#!/usr/bin/python

import fontforge, psMat, sys, os

f1 = fontforge.open(os.path.abspath(sys.argv[1]))
f2 = fontforge.open(os.path.abspath(sys.argv[2]))

map = {
    0x00f1 : 0x02C6,
    0x00f2 : 0x02C7,
    0x00f3 : 0xA788,
    0x00f4 : 0x02EC,
    0x00f5 : 0x02CD,
    0x00f6 : 0x02C9 }

for inid, outid in map.items() :
    e = f2.findEncodingSlot(inid)
    if e != -1 :
        g = f2[e]
    targ = f1.createChar(outid)
    f1.selection.select(targ)
    g.draw(targ.glyphPen())
    targ.transform(psMat.scale(0.4695))
f1.generate(sys.argv[3])
